/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  subtitle?: string;
  albumImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  instagramUrl?: string;
  spotifyUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/queries/home-page.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{  title,  subtitle,  albumImage{    asset->{      _id,      url,      metadata{ lqip, dimensions{ width, height } }    },    alt,    hotspot,    crop  }}
export type HOME_PAGE_QUERY_RESULT =
  | {
      title: string;
      subtitle: null;
      albumImage: null;
    }
  | {
      title: string | null;
      subtitle: null;
      albumImage: null;
    }
  | {
      title: string;
      subtitle: string | null;
      albumImage: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
    }
  | null;

// Source: sanity/queries/site-settings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{  title,  description,  instagramUrl,  spotifyUrl}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      title: string;
      description: null;
      instagramUrl: null;
      spotifyUrl: null;
    }
  | {
      title: string;
      description: string;
      instagramUrl: string | null;
      spotifyUrl: string | null;
    }
  | {
      title: string | null;
      description: string | null;
      instagramUrl: null;
      spotifyUrl: null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_id == "homePage"][0]{\n  title,\n  subtitle,\n  albumImage{\n    asset->{\n      _id,\n      url,\n      metadata{ lqip, dimensions{ width, height } }\n    },\n    alt,\n    hotspot,\n    crop\n  }\n}': HOME_PAGE_QUERY_RESULT;
    '*[_id == "siteSettings"][0]{\n  title,\n  description,\n  instagramUrl,\n  spotifyUrl\n}': SITE_SETTINGS_QUERY_RESULT;
  }
}
