/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HomePageGallery = {
  _type: "homePageGallery";
  images?: Array<
    {
      _key: string;
    } & HomePageImage
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HomePageImage = {
  _type: "homePageImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type HomePageMerch = {
  _type: "homePageMerch";
  title?: string;
  description?: string;
  buttonText?: string;
};

export type HomePageEvents = {
  _type: "homePageEvents";
  title?: string;
  hidePastEvents?: boolean;
  events?: Array<
    {
      _key: string;
    } & HomePageEvent
  >;
};

export type HomePageEvent = {
  _type: "homePageEvent";
  eventDate: string;
  title?: string;
  description?: string;
  link?: string;
};

export type HomePageMorgan = {
  _type: "homePageMorgan";
  title?: string;
  text?: string;
  image?: HomePageImage;
  buttonText?: string;
};

export type HomePageHero = {
  _type: "homePageHero";
  title?: string;
  subtitle?: string;
  buttonText?: string;
  albumImage?: HomePageImage;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: HomePageHero;
  morgan?: HomePageMorgan;
  events?: HomePageEvents;
  merch?: HomePageMerch;
  gallery?: HomePageGallery;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  instagramUrl?: string;
  spotifyUrl?: string;
  bandcampMerchUrl?: string;
};

export type AboutPageSection = {
  _type: "aboutPageSection";
  title: string;
  text: string;
  image?: HomePageImage;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  morganSection?: AboutPageSection;
  bandSection?: AboutPageSection;
  additionalSections?: Array<
    {
      _key: string;
    } & AboutPageSection
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | HomePageGallery
  | SanityImageAssetReference
  | HomePageImage
  | HomePageMerch
  | HomePageEvents
  | HomePageEvent
  | HomePageMorgan
  | HomePageHero
  | HomePage
  | SiteSettings
  | AboutPageSection
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/queries/about-page.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0]{  "morganSection": morganSection{  _key,  title,  text,  image{    alt,    asset->{ _id, url }  }},  "bandSection": bandSection{  _key,  title,  text,  image{    alt,    asset->{ _id, url }  }},  "additionalSections": additionalSections[]{  _key,  title,  text,  image{    alt,    asset->{ _id, url }  }}}
export type ABOUT_PAGE_QUERY_RESULT =
  | {
      morganSection: null;
      bandSection: null;
      additionalSections: null;
    }
  | {
      morganSection: {
        _key: null;
        title: string;
        text: string;
        image: {
          alt: string | null;
          asset: {
            _id: string;
            url: string;
          } | null;
        } | null;
      } | null;
      bandSection: {
        _key: null;
        title: string;
        text: string;
        image: {
          alt: string | null;
          asset: {
            _id: string;
            url: string;
          } | null;
        } | null;
      } | null;
      additionalSections: Array<{
        _key: string;
        title: string;
        text: string;
        image: {
          alt: string | null;
          asset: {
            _id: string;
            url: string;
          } | null;
        } | null;
      }> | null;
    }
  | null;

// Source: sanity/queries/home-page.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{  "hero": {    "title": coalesce(hero.title, title),    "subtitle": coalesce(hero.subtitle, subtitle),    "buttonText": coalesce(hero.buttonText, "Listen Now"),    "albumImage": coalesce(hero.albumImage, albumImage){      asset->{        _id,        url,        metadata{ lqip, dimensions{ width, height } }      },      alt,      hotspot,      crop    }  },  morgan{    title,    text,    buttonText,    image{      asset->{        _id,        url,        metadata{ lqip, dimensions{ width, height } }      },      alt,      hotspot,      crop    }  },  events{    title,    hidePastEvents,    events[]{      _key,      eventDate,      title,      description,      link    }  },  merch{    title,    description,    buttonText  },  gallery{    images[]{      _key,      asset->{        _id,        url,        metadata{ lqip, dimensions{ width, height } }      },      alt,      hotspot,      crop    }  }}
export type HOME_PAGE_QUERY_RESULT =
  | {
      hero: {
        title: null;
        subtitle: null;
        buttonText: "Listen Now";
        albumImage: null;
      };
      morgan: null;
      events: null;
      merch: null;
      gallery: null;
    }
  | {
      hero: {
        title: string;
        subtitle: null;
        buttonText: "Listen Now";
        albumImage: null;
      };
      morgan: null;
      events: null;
      merch: null;
      gallery: null;
    }
  | {
      hero: {
        title: string | null;
        subtitle: null;
        buttonText: "Listen Now";
        albumImage: null;
      };
      morgan: null;
      events: null;
      merch: null;
      gallery: null;
    }
  | {
      hero: {
        title: string | null;
        subtitle: string | null;
        buttonText: string | "Listen Now";
        albumImage: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
              } | null;
            } | null;
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
      };
      morgan: {
        title: string | null;
        text: string | null;
        buttonText: string | null;
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
              } | null;
            } | null;
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
      } | null;
      events: {
        title: string | null;
        hidePastEvents: boolean | null;
        events: Array<{
          _key: string;
          eventDate: string;
          title: string | null;
          description: string | null;
          link: string | null;
        }> | null;
      } | null;
      merch: {
        title: string | null;
        description: string | null;
        buttonText: string | null;
      } | null;
      gallery: {
        images: Array<{
          _key: string;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
              } | null;
            } | null;
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        }> | null;
      } | null;
    }
  | null;

// Source: sanity/queries/site-settings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{  title,  description,  instagramUrl,  spotifyUrl,  bandcampMerchUrl}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      title: null;
      description: null;
      instagramUrl: null;
      spotifyUrl: null;
      bandcampMerchUrl: null;
    }
  | {
      title: string | null;
      description: string | null;
      instagramUrl: null;
      spotifyUrl: null;
      bandcampMerchUrl: null;
    }
  | {
      title: string;
      description: string;
      instagramUrl: string | null;
      spotifyUrl: string | null;
      bandcampMerchUrl: string | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_id == "aboutPage"][0]{\n  "morganSection": morganSection{\n  _key,\n  title,\n  text,\n  image{\n    alt,\n    asset->{ _id, url }\n  }\n},\n  "bandSection": bandSection{\n  _key,\n  title,\n  text,\n  image{\n    alt,\n    asset->{ _id, url }\n  }\n},\n  "additionalSections": additionalSections[]{\n  _key,\n  title,\n  text,\n  image{\n    alt,\n    asset->{ _id, url }\n  }\n}\n}': ABOUT_PAGE_QUERY_RESULT;
    '*[_id == "homePage"][0]{\n  "hero": {\n    "title": coalesce(hero.title, title),\n    "subtitle": coalesce(hero.subtitle, subtitle),\n    "buttonText": coalesce(hero.buttonText, "Listen Now"),\n    "albumImage": coalesce(hero.albumImage, albumImage){\n      asset->{\n        _id,\n        url,\n        metadata{ lqip, dimensions{ width, height } }\n      },\n      alt,\n      hotspot,\n      crop\n    }\n  },\n  morgan{\n    title,\n    text,\n    buttonText,\n    image{\n      asset->{\n        _id,\n        url,\n        metadata{ lqip, dimensions{ width, height } }\n      },\n      alt,\n      hotspot,\n      crop\n    }\n  },\n  events{\n    title,\n    hidePastEvents,\n    events[]{\n      _key,\n      eventDate,\n      title,\n      description,\n      link\n    }\n  },\n  merch{\n    title,\n    description,\n    buttonText\n  },\n  gallery{\n    images[]{\n      _key,\n      asset->{\n        _id,\n        url,\n        metadata{ lqip, dimensions{ width, height } }\n      },\n      alt,\n      hotspot,\n      crop\n    }\n  }\n}': HOME_PAGE_QUERY_RESULT;
    '*[_id == "siteSettings"][0]{\n  title,\n  description,\n  instagramUrl,\n  spotifyUrl,\n  bandcampMerchUrl\n}': SITE_SETTINGS_QUERY_RESULT;
  }
}
